#!/bin/bash
riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32im -nostartfiles -ffreestanding \
-I $RVATOM_LIB/include -L $RVATOM_LIB -T $RVATOM_LIB/link/link.ld -DTARGET_ATOMBONES \
$* -lcatom -Wl,--gc-sections
